name: yuno

packages:
  - ./yuno_sdk
  - ./yuno_sdk_core
  - ./yuno_sdk_android
  - ./yuno_sdk_foundation
  - ./yuno_sdk_platform_interface
ignore:
  - examples

scripts:
  # Script to generate coverage and open the report
  coverage:
    description: Generate coverage and open in default browser
    exec: |
      flutter test --coverage
      lcov --remove coverage/lcov.info 'lib/**/*.g.dart' 'lib/**/generated/*.dart' -o coverage/lcov_filtered.info
      genhtml coverage/lcov_filtered.info -o coverage/html
    packageFilters:
      ignore: [yuno_sdk_android, yuno_sdk_foundation]
