name: yuno

packages:
  - ./yuno_sdk
  - ./yuno_sdk_core
  - ./yuno_sdk_android
  - ./yuno_sdk_foundation
  - ./yuno_sdk_platform_interface
ignore:
  - examples

scripts:
  # Script to generate coverage and open the report
  test:
    description: Generate test, badge, and open the report
    exec: |
      # Generate Flutter test coverage
      flutter test --coverage
    packageFilters:
      ignore: [yuno_sdk_android, yuno_sdk_foundation]   
  local_test:
    description: Generate test, badge, and open the report
    exec: |
      # Generate Flutter test coverage
      flutter test --coverage
      
      # Filter out generated files from the coverage report
      lcov --remove coverage/lcov.info 'lib/**/*.g.dart' 'lib/**/generated/*.dart' -o coverage/lcov_filtered.info
      
      # Generate an HTML report
      genhtml coverage/lcov_filtered.info -o coverage/html

      # Open the HTML report (macOS specific)
      if [ "$(uname)" == "Darwin" ]; then
        open coverage/html/index.html
      fi
    
    packageFilters:
      ignore: [yuno_sdk_android, yuno_sdk_foundation]