name: yuno

packages:
  - ./yuno_sdk
  - ./yuno_sdk_core
  - ./yuno_sdk_android
  - ./yuno_sdk_foundation
  - ./yuno_sdk_platform_interface
ignore:
  - examples

scripts:
  # Script to generate coverage and open the report
  coverage:
    description: Generate coverage, badge, and open the report
    exec: |
      # Generate Flutter test coverage
      flutter test --coverage
      
      # Filter out generated files from the coverage report
      lcov --remove coverage/lcov.info 'lib/**/*.g.dart' 'lib/**/generated/*.dart' -o coverage/lcov_filtered.info
      
      # Generate an HTML report
      genhtml coverage/lcov_filtered.info -o coverage/html

      # Open the HTML report (macOS specific)
      if [ "$(uname)" == "Darwin" ]; then
        #open coverage/html/index.html
      fi

      # Move to the desired directory
      cd ./yuno_sdk

      # Calculate coverage percentage
      COVERAGE=$(lcov --summary ../coverage/lcov_filtered.info | grep "lines......" | cut -d ' ' -f 4 | cut -d '%' -f 1)
      
      # Generate the badge URL
      BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen?style=for-the-badge"
      
      # Fetch the badge image and save it
      curl -o coverage_badge.svg $BADGE_URL

      # Log success
      echo "Coverage badge created with ${COVERAGE}% coverage"
    packageFilters:
      ignore: [yuno_sdk_android, yuno_sdk_foundation]
