enum Keys {
  apiKey,
  countryCode,
  alias,
  checkoutSession,
  accentColor,
  buttonBackgrounColor,
  buttonTitleBackgrounColor,
  buttonBorderBackgrounColor,
  secondaryButtonBackgrounColor,
  secondaryButtonTitleBackgrounColor,
  secondaryButtonBorderBackgrounColor,
  disableButtonBackgrounColor,
  disableButtonTitleBackgrounColor,
  checkboxColor,
}
